apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulator
    name: webapp
    resources: {}
    volumeMounts:
    - mountPath: /log
      name: log-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
  - name: log-volume
    hostPath:
      # directory location on host
      path: /var/log/webapp
      # this field is optional
      type: Directory

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulator
    name: webapp
    resources: {}
    volumeMounts:
    - mountPath: /log
      name: log-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: claim-log-1
---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx:alpine 
    name: nginx
    volumeMounts:
      - name: local-persistent-storage
        mountPath: /var/www/html
  
  volumes:
  - name: local-persistent-storage
    persistentVolumeClaim:
      claimName: local-pvc

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

