apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    command: ["echo", "hello"]
    args: ["Durgaprasad", "Polavarapu"]
    volumeMounts:
      - mountPath: /mnt
        name: my-date
      - mountPath: /ebs
        name: ebs
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  volumes:
    - name: my-date
      hostPath:
        path: /data
        type: directory
    - name: ebs
      awsElasticBlockStore:
        volumeID: <volume-id>
        fsType: ext4