apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
  - name: lemon
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - sleep
      - "1000"

  - name: gold
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"