apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
  labels:
      name: webapp-green
spec:
  containers:
  - name: simple-webapp
    image: kodekloud/webapp-color
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["python", "app.py"]
    args: ["--color", "pink"]