---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
  labels:
    name: myapp
    tier: frontend
spec:
  securityContext:
    runAsUser: 1010
  containers:
  - command: ["sleep", "4800"]
    args:
      - ""
    image: ubuntu
    name: ubuntu-sleeper